name: Tests

on: [pull_request]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        id: setup
        uses: kitbagjs/actions-setup-project@main

      - name: Run unit tests
        run: npm run test

  type-test:
    name: Type Tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        id: setup
        uses: kitbagjs/actions-setup-project@main

      - name: Run unit tests
        run: npm run test:types